pipelineJob(" TestFrameSamp ") {
    description("""Deploy dataprobe TestFrame to different Layers <br/>
   <font color="red">***This job was automatically generated by the seed job. DO NOT EDIT!</font>""")

    parameters {
        choiceParam('SELECT ENVIRONMENT', ['dev-db (default)', 'qa-db', 'prod-db'])
    }
}